config/routes.rb
Wallbase::Application.routes.draw do
  resources :opening_pages

  # Main resources
  resources :collections
  resources :collection_sections
  resources :style_types, :path => "style-types"
  resources :profiles
  resources :colors
  resources :color_palettes, :path => "color-palettes"

  # Johnsonite API routes
  match '/samplecart' => 'filters#samplecart', as: 'sample_cart', via: [:get, :post]

  # Root path
  root :to => 'filters#index'
  post '/' => 'filters#index'
  get '/color-pallete-chart' => 'filters#color_palettes', as: 'color_palette_chart'
end

app/models/collection.rb
class Collection < ActiveRecord::Base  
  validates_presence_of :name
  
  has_many :style_types, dependent: :destroy
  has_many :profiles, through: :style_types, dependent: :destroy
  has_many :collection_sections, dependent: :destroy
  accepts_nested_attributes_for :collection_sections, allow_destroy: true
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_filter :authenticate

  def index
    @collections = Collection.order :name
  end

  def show
    @collection = Collection.find params[:id]
  end

  def new
    @collection = Collection.new    
  end

  def edit
    @collection = Collection.find params[:id]
  end

  def create
    @collection = Collection.new(collection_params)
    if @collection.save
      redirect_to collection_path(@collection), notice: 'Create Collection'
    else
      render :new
    end
  end

  def update
    @collection = Collection.find params[:id]

    if @collection.update_attributes(collection_params)
      redirect_to collection_path(@collection), notice: 'Updated Collection'
    else
      render :edit
    end
  end

  def destroy
    colleciton = Collection.find params[:id]
    colleciton.destroy
    flash[:error] = "Deleted Collection"
    redirect_to collections_path
  end

  private

  def collection_params
    params.require(:collection).permit(
      :name,
      :collection_description,
      :icon_1,
      :icon_2,
      :icon_3,
      :icon_4,
      :icon_5,
      collection_sections_attributes: [:title, :body, :_destroy])
  end
end

app/views/collections/_collection_section_fields.html.erb
<fieldset>
  <h5 class="subheader">Add Section</h5>
  <%= f.text_field :title, placeholder: 'Enter title text here.' %><br />  
  <%= f.text_area :body, placeholder: 'Enter body text here.' %><br />  
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields small alert button" %>
</fieldset>

app/views/collections/edit.html.erb
<h3>Update: <span class='label'><%= @collection.name %></span></h3>
<hr />
<%= form_for @collection do |f| %>
  <%= f.error_messages %>
  <%= f.text_field :name, placeholder: "Collection Name" %>  
  <%= f.text_area :collection_description, placeholder: "Type description here." %>

  <ul id="spec-image-list" class="large-block-grid-5">
    <li>
      <label>
        <%= f.check_box :icon_1 %>
        <%= image_tag "Icon_BIAQ.png" %>
      </label>
    </li>
    <li>
      <label>
        <%= f.check_box :icon_2 %>
        <%= image_tag "icon_floorscore.png" %>
      </label>
    </li>
    <li>
      <label>
        <%= f.check_box :icon_3 %>
        <%= image_tag "icon_NSF.png" %>
       </label>
    </li>
    <li>
      <label>
        <%= f.check_box :icon_4 %>
        <%= image_tag "icon_phthalateFree.png" %>
       </label>
    </li>
    <li>
      <label>
        <%= f.check_box :icon_5 %>
        <%= image_tag "icon_phthalateHalogen.png" %>
       </label>
    </li>
  </ul>
  <hr />
  <%= link_to_add_fields "Add Section", f, :collection_sections, class: 'small success button' %>
  
  <div class="row">
    <div class="large-12 columns">      
       <%= f.fields_for :collection_sections do |builder| %>
         <%= render 'collection_section_fields', f: builder %>
       <% end %>
    </div>
  </div>

  <%= f.submit "Update Collection", class: 'small button' %> <%= link_to "Cancel", collection_path(@collection), class: 'small alert button' %>
<% end %>

app/views/collections/index.html.erb
<h3 class="subheader">List of Collections</h3>

<hr />

<div class="large-4 columns">
<%= link_to "+ Add Collection", new_collection_path, class: 'success button radius expand' %>
<% @collections.each do |c| %>
  <%= link_to c.name, collection_path(c), class: 'button radius expand' %><br />
<% end %>
</div>

app/views/collections/new.html.erb
<h3>Create a Collection area</h3>
<hr />

<%= form_for @collection do |f| %>
  <%= f.error_messages %>
  <%= f.text_field :name, placeholder: "Collection Name" %>  
  <%= f.text_area :collection_description, placeholder: "Type description here." %>

  <ul id="spec-image-list" class="large-block-grid-5">
    <li>
      <label>
        <%= f.check_box :icon_1 %>
        <%= image_tag "Icon_BIAQ.png" %>
      </label>
    </li>
    <li>
      <label>
        <%= f.check_box :icon_2 %>
        <%= image_tag "icon_floorscore.png" %>
      </label>
    </li>
    <li>
      <label>
        <%= f.check_box :icon_3 %>
        <%= image_tag "icon_NSF.png" %>
       </label>
    </li>
    <li>
      <label>
        <%= f.check_box :icon_4 %>
        <%= image_tag "icon_phthalateFree.png" %>
       </label>
    </li>
    <li>
      <label>
        <%= f.check_box :icon_5 %>
        <%= image_tag "icon_phthalateHalogen.png" %>
       </label>
    </li>
  </ul>
  <hr />
  <%= link_to_add_fields "Add Section", f, :collection_sections, class: 'small success button' %>
  
  <div class="row">
    <div class="large-12 columns">      
       <%= f.fields_for :collection_sections do |builder| %>
         <%= render 'collection_section_fields', f: builder %>
       <% end %>
    </div>
  </div>

  <%= f.submit "Create Collection", class: 'success button small' %> <%= link_to "Cancel", collections_path, class: 'alert button small' %>
<% end %>

app/views/collections/show.html.erb
<style>
li {list-style-type: none;}
a.red {color: red;}
</style>
<h3 class="subheader">List of Collections</h3>
<hr />

<div class="large-4 columns">
  <%= link_to "+ Add Collection", new_collection_path, class: 'success button radius expand' %>
  <% Collection.order(:name).each do |c| %>
  <%= link_to c.name, collection_path(c), class: 'button radius expand' %><br />
<% end %>
</div>

<div class="large-8 columns">  
  <h5><%= @collection.name %></h5>
  <%= link_to "+ Add Style", new_style_type_path(collection_id: @collection.id), class: 'success small button radius ' %>    
  <%= link_to "Delete Collection", collection_path(@collection), method: :delete, class: 'right alert small button radius ', data: {confirm: "Are you sure?"} %>    <%= link_to "Edit Collection", edit_collection_path(@collection), class: 'right small button nice ' %>
  <br />
  <br />
  <% @collection.style_types.each do |s| %>
    <div class="row">
      <div class="large-12 columns panel">
            <%= s.name %> (<%= pluralize s.profiles.count, 'profile' %>)
            <%= link_to "Delete Style", style_type_path(s), data: {confirm: "Are you sure?"}, :method => :delete, class: 'alert small button  right' %>
            <%= link_to "Edit Style", edit_style_type_path(s), class: 'small button  right' %>
        <br />
        <hr />
        <%= link_to "+ Add Profile", new_profile_path(id: s.id), class: 'success small button radius' %>
        <div class="row">
          <div class="large-12 columns">
            <ul>
            <% s.profiles.each do |p| %>
              <li><%= p.size %>" <%= p.uuid %> <%= link_to "Edit", edit_profile_path(p) %> | <%= link_to "Delete", profile_path(p), class: 'red', method: :delete, data: {confirm: "Are you sure?"} %>
              <br />
              <% p.color_palettes.order(:name).each do |cp| %>
                <span class="color-palette color-palette-<%= cp.name %>"><%= cp.name == 'Selects' ? '&nbsp;'.html_safe : cp.name %></span>
              <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <% @collection.collection_sections.each do |cs| %>
    <span style="text-transform: uppercase">
      <h5><%= cs.title %></h5>
      <% cs.body.each_line do |line| %>
        <%= line %><br />
      <% end %>
    <span>
  <% end %>
</div>