config/routes.rb
Wallbase::Application.routes.draw do
  resources :opening_pages

  # Main resources
  resources :collections
  resources :collection_sections
  resources :style_types, :path => "style-types"
  resources :profiles
  resources :colors
  resources :color_palettes, :path => "color-palettes"

  # Johnsonite API routes
  match '/samplecart' => 'filters#samplecart', as: 'sample_cart', via: [:get, :post]

  # Root path
  root :to => 'filters#index'
  post '/' => 'filters#index'
  get '/color-pallete-chart' => 'filters#color_palettes', as: 'color_palette_chart'
end

app/models/color_palette.rb
class ColorPalette < ActiveRecord::Base
  validates_presence_of :name, :order_number
  
  has_many :colors, dependent: :destroy
  has_many :profile_color_palettes, dependent: :destroy
  has_many :profiles, through: :profile_color_palettes, dependent: :destroy

  scope :ordered, -> { order(:order_number) }
  scope :labels, -> { order(:id).limit(6) }
end

app/controllers/color_palettes_controller.rb
class ColorPalettesController < ApplicationController
  before_filter :authenticate

  def index
    @color_palettes = ColorPalette.ordered
  end

  def new
    @color_palette = ColorPalette.new
  end

  def edit
    @color_palette = ColorPalette.find params[:id]
  end

  def create
    @color_palette = ColorPalette.new params[:color_palette]
    if @color_palette.save
      redirect_to color_palettes_path, notice: 'Create Color Palette'
    else
      render :new
    end
  end

  def update
    @color_palette = ColorPalette.find params[:id]

    if @color_palette.update_attributes params[:color_palette]
      redirect_to color_palettes_path, notice: 'Updated Color Palette'
    else
      render :edit
    end
  end

  def destroy
    color_palette = ColorPalette.find params[:id]
    color_palette.destroy
    flash[:error] = "Deleted Color Palette"
    redirect_to color_palettes_path
  end
end

app/helpers/color_palettes_helper.rb
module ColorPalettesHelper  
  def admin_color_swatch_for(color_palette)
    divs = ""
    if color_palette.name.downcase == "selects"            
      Color.where(:selects => true).order(:color_number).each do |color|
        divs += "<div class='large-3 columns color-swatch'><div class='swatch shadow' style='background: ##{color.hex};'></div><br />
                       <b>#{display_color_number color.color_number}</b> #{color.name}<b> #{color.color_foundation}</b> #{in_selects? color}<br />"
        divs += link_to "Edit", edit_color_path(color)
        divs += " | "
        divs += link_to "Delete", color_path(color), method: :delete, class: 'red', data: {confirm: "Are you sure?"}
        divs += "</div>"
      end
    elsif color_palette.name.downcase == "wall art"            
      color_palette.colors.order(:color_number).each do |color|
        divs += "<div class='large-3 columns color-swatch'><div class='swatch shadow' style='background: url(/assets/wallart/#{color.color_number}.jpg);'></div><br />
                       <b>#{color.color_number}</b> #{color.name}<b> #{color.color_foundation}</b> #{in_selects? color}<br />"
        divs += link_to "Edit", edit_color_path(color)
        divs += " | "
        divs += link_to "Delete", color_path(color), method: :delete, class: 'red', data: {confirm: "Are you sure?"}
        divs += "</div>"
      end
    elsif color_palette.name.downcase == "wood"            
      color_palette.colors.order(:color_number).each do |color|
        divs += "<div class='large-3 columns color-swatch'><div class='swatch shadow' style='background: url(/assets/wood/#{color.color_number}.jpg);'></div><br />
                       <b>#{color.color_number}</b> #{color.name}<b> #{color.color_foundation}</b> #{in_selects? color}<br />"
        divs += link_to "Edit", edit_color_path(color)
        divs += " | "
        divs += link_to "Delete", color_path(color), method: :delete, class: 'red', data: {confirm: "Are you sure?"}
        divs += "</div>"
      end
    elsif color_palette.name.downcase == "stone"            
      color_palette.colors.order(:color_number).each do |color|
        divs += "<div class='large-3 columns color-swatch'><div class='swatch shadow' style='background: url(/assets/stone/#{color.color_number}.jpg);'></div><br />
                       <b>#{color.color_number}</b> #{color.name}<b> #{color.color_foundation}</b> #{in_selects? color}<br />"
        divs += link_to "Edit", edit_color_path(color)
        divs += " | "
        divs += link_to "Delete", color_path(color), method: :delete, class: 'red', data: {confirm: "Are you sure?"}
        divs += "</div>"
      end
    else
      color_palette.colors.order(:color_number).each do |color|
        divs += "<div class='large-3 columns color-swatch'><div class='swatch shadow' style='background: ##{color.hex};'></div><br />
                       <b>#{display_color_number color.color_number}</b> #{color.name}<b> #{color.color_foundation}</b> #{in_selects? color}<br />"
        divs += link_to "Edit", edit_color_path(color)
        divs += " | "
        divs += link_to "Delete", color_path(color), method: :delete, class: 'red', data: {confirm: "Are you sure?"}
        divs += "</div>"
      end
    end

    divs.html_safe
  end
end

app/views/color_palettes/edit.html.erb
<h3>Update: <span class='label'><%= @color_palette.name %></span></h3>
<hr />
<%= form_for @color_palette do |f| %>
  <%= f.error_messages %>

  <%= f.label :order_number %>
  <%= f.select :order_number, 1..ColorPalette.all.count %>
  <br />
  <br />
  
  <%= f.text_field :name, placeholder: "Color Palette Name" %>

  <%= f.submit "Update Color Palette", class: 'button nice radius' %> <%= link_to "Cancel", color_palettes_path, class: 'alert button nice radius' %>
<% end %>

app/views/color_palettes/index.html.erb
<style>
.swatch {
  width: 50px;
  height: 50px;
  margin: 0 auto;
  border: 3px solid whitesmoke;
}

.shadow {
  box-shadow: 0 1px 3px #AAA;
}

.color-swatch {
  margin-top: 12px;
  padding-bottom: 20px;
  text-align: center;
  border-bottom: 1px solid #CCC;
}
.red {
  color: red;
}
</style>

<%= link_to "+ Add Color Palette", new_color_palette_path, class: 'success button nice radius right' %>
<h3 class="subheader">List of Color Palettes</h3>

<hr />
<br />

<div class="section-container tabs" data-section>
<% @color_palettes.each do |color_palette| %>  
  <% if color_palette.id.to_s == params[:color_palette_id].to_s %>
    <section class="section active">
  <% else %>
    <section class="section">
  <% end %>

    <div class="title" style="width: <%= 100.0 / @color_palettes.count.to_f %>%">
        <% if color_palette.name == "Selects" %>     
          <h5 style="text-align: center"><%= color_palette.name[0..2] %> (<%= Color.where(:selects => true).count %>)</h5>
        <% else %>
          <h5 style="text-align: center"><%= color_palette.name[0..2] %> (<%= color_palette.colors.count %>)</h5>
        <% end %>
    </div>

    <div class="content">
      <br />
      <div class="row">
        <div class="large-3 columns">
          <%= link_to "+ Add Color", new_color_path(id: color_palette.id), class: 'success small button nice radius' %>
        </div>        
        <div class="large-5 large-offset-4 columns">
          <ul class="inline-list">
            <li><%= link_to "Edit Color Palette", edit_color_palette_path(color_palette), class: 'small button nice radius' %></li>
            <li><%= link_to "Delete Color Palette", color_palette_path(color_palette), method: :delete, class: 'alert small button nice radius', data: {confirm: "Are you sure?"} %></li>
          </ul>
        </div>
        <hr />
      </div>
      <div class="row">
        <%= admin_color_swatch_for color_palette %>
      </div>
    </div>
  </section>
<% end %>
</div>

app/views/color_palettes/new.html.erb
<h3>Create a Color Palette</h3>
<hr />

<%= form_for @color_palette do |f| %>
  <%= f.error_messages %>

  <%= f.label :order_number %>
  <%= f.select :order_number, 1..ColorPalette.all.count+1, :selected => ColorPalette.all.count+1 %>
  <br />
  <br />
  <%= f.text_field :name, placeholder: "Color Palette Name" %>
  
  <%= f.submit "Create Color Palette", class: 'success button nice radius' %> <%= link_to "Cancel", color_palettes_path, class: 'alert button nice radius' %>
<% end %>