config/routes.rb
Wallbase::Application.routes.draw do
  resources :opening_pages

  # Main resources
  resources :collections
  resources :collection_sections
  resources :style_types, :path => "style-types"
  resources :profiles
  resources :colors
  resources :color_palettes, :path => "color-palettes"

  # Johnsonite API routes
  match '/samplecart' => 'filters#samplecart', as: 'sample_cart', via: [:get, :post]

  # Root path
  root :to => 'filters#index'
  post '/' => 'filters#index'
  get '/color-pallete-chart' => 'filters#color_palettes', as: 'color_palette_chart'
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  SKU_REGEX = /\A[A-Z]{1,4}-[X]{3}-[A-Z0-9]{1,4}\z/

  validates_presence_of :style_type_id, :uuid, :size
  
  belongs_to :style_type
  has_one :collection, through: :style_type, dependent: :destroy
  has_many :collection_sections, through: :collection
  has_many :profile_color_palettes, dependent: :destroy
  has_many :color_palettes, through: :profile_color_palettes, dependent: :destroy
  has_many :colors, through: :color_palettes, dependent: :destroy

  has_attached_file :profile_image
  has_attached_file :corner_image
  
  do_not_validate_attachment_file_type :corner_image
  do_not_validate_attachment_file_type :profile_image

  validates_format_of :uuid, with: SKU_REGEX, message: 'is in the wrong format. Do not mess with skus, they are powerful. They directly affect the sample cart. They should look like: CC-XXX-4'

  scope :ordered, -> { order("id") }

  def profile_image_url
    self.profile_image.blank? ? "missing.jpg" : self.profile_image.url
  end

  def corner_image_url
    self.corner_image.blank? ? "missing.jpg" : self.corner_image.url
  end

  def name
    self.uuid
  end

  def related_products
    self.collection.style_types.where("style_types.id != ?", style_type.id).order('random()').limit(5)
  end

  def color_palette_width_in_percent
    "#{100.0 / color_palettes.count.to_f}%"
  end

  def self.missing_images(type='corner')
    folder       = type == 'profile' ? 'profile_images' : 'corner_images'
    image_suffex = type == 'profile' ? 'profile' : 'image'

    missing_images = []
    Profile.all.each do |p|
      unless File.exists?(File.join(Rails.root, "app/assets/images/#{folder}/#{p.style_type.name.capitalize}-#{p.name}-#{image_suffex}.jpg"))
        missing_images << "Missing: #{p.id} :: #{p.style_type.name}".ljust(39) + "| Should be: " + "#{p.style_type.name.capitalize}-#{p.name}-#{image_suffex}.jpg".ljust(50).yellow + '*'.red
      end
    end
    length = missing_images.first.length-16
    puts ("*".red)*length
    missing_images.each {|n| puts "#{'*'.red} #{n}"}
    puts ("*".red)*length
    puts "\nTotal: \e[32m#{missing_images.count}\e[0m\n"
  end
end

app/controllers/filters_controller.rb
class FiltersController < ApplicationController
  layout 'filter'

  def index
    @collections    = Collection.order(:name)
    @color_palettes = ColorPalette.ordered    
    @style_names    = StyleType.select('distinct name').order(:name).map {|st| [st.name]}
    @materials      = StyleType.select('distinct material').where("material != ''").order(:material).map {|m| [m.material]}

    if params[:profile_id].present?
      @profile = Profile.includes(        
        :style_type,
        :collection,
        :collection_sections)
        .find(params[:profile_id])
    end

    # begin filtering
    style_type_filter = StyleType.includes(:collection, :profiles).joins(:profiles)

    # collections
    if params[:collection_id].present?
      style_type_filter = style_type_filter.where('collection_id = ?', params[:collection_id])
    end

    # styles
    if params[:style_type_name].present?
      style_type_filter = style_type_filter.where('style_types.name = ?', params[:style_type_name])
    end

    # materials
    if params[:material].present?
      style_type_filter = style_type_filter.where('style_types.material LIKE ?', "%#{params[:material]}")
    end

    # color palettes
    if params[:color_palette_ids].present?      
      params[:color_palette_ids].each do |cpid|
        sql = <<-END_SQL
          EXISTS ( SELECT 1
                   FROM profile_color_palettes
                   WHERE profile_id = profiles.id                   
                   AND color_palette_id = ?)
        END_SQL

        style_type_filter = style_type_filter.where(sql, cpid.to_i)      
      end
    end

    @style_types = style_type_filter.order('style_types.collection_id').limit(30)
  end

  def samplecart    
    johnsonite_api_path = cookies[:wallbase_sample_skus] || ''
    johnsonite_api_path += ',' unless johnsonite_api_path.blank?

    params[:wallbase_skus].each do |sku|
      johnsonite_api_path += "#{sku},"
    end
    
    cookies[:wallbase_sample_skus] = {
      value: johnsonite_api_path.split(',').uniq.join(','),
      domain: '.johnsonite.com'
    }
    flash[:notice] = "Added skus to sample cart!"
    render text: '<script>document.domain = "johnsonite.com";parent.GoToCart();</script>'
  end

  def color_palettes
    @color_palettes = ColorPalette.ordered    
  end
end

app/helpers/filters_helper.rb
# encoding: UTF-8
module FiltersHelper
  def nice_color_palette_name_for(color_palette)
    if color_palette.name == 'Selects'
      'Selects Palette'
    elsif color_palette.name == 'W'
      'Wall Art'
    elsif color_palette.name == 'Wood'
      'Wood Patterns (Masquerade)'
    elsif color_palette.name == 'Stone'
      'Stone Patterns (Masquerade)'
    elsif color_palette.name == 'Wall Art'
      'Wall Art Patterns'
    else
      "Palette #{color_palette.name}"
    end
  end

  def nice_checkbox_palette_name_for(color_palette)
    if color_palette.name == 'Selects'
      '<span class="color-palette round color-palette-Selects" style=""></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Selects Palette'.html_safe
    elsif color_palette.name == 'W'
      '&nbsp;<span class="color-palette round color-palette-W" style="left:20px !important">W</span> Wall Art'.html_safe
    elsif color_palette.name == 'Wood'
      'Masquerade (Standard)'
    elsif color_palette.name == 'Stone'
      'hide'
    elsif color_palette.name == 'Wall Art'
      'Wall Art Patterns'
    else
      "&nbsp;<span class='color-palette round color-palette-#{color_palette.name}'>#{color_palette.name}</span> Palette #{color_palette.name}".html_safe
    end
  end

  def colors_for(color_palette)
    list_items = ""
    if color_palette.name == "Selects"            
      Color.where(selects: true).each do |color|
      list_items += "<li style='display:inline-block;margin: 0 8px; width: 50px;' class='has-tip' data-tooltip title='#{display_color_number color.color_number} #{color.name} #{color.color_foundation}'>               
            <label class='color-label' style='background: ##{color.hex}' data-color='#{color.hex}'>
              <input type='checkbox' data-sku='#{@profile.uuid.gsub('XXX', display_color_number(color.color_number))}' value='#{display_color_number color.color_number} #{color.name}' style='display:none'/>
            </label>
          </li>"
      end
    elsif color_palette.name == "Wall Art"
      color_palette.colors.each do |color|
      list_items += "<li style='display:inline-block;margin: 0 8px; width: 50px;' class='has-tip' data-tooltip title='#{display_color_number color.color_number} #{color.name} #{color.color_foundation}'>               
          <label class='color-label' style='background: url(/assets/wallart/#{color.color_number}.jpg)' data-color='#{color.hex}'>
            <input type='checkbox' data-sku='#{@profile.uuid.gsub('XXX', color.color_number)}' value='#{color.color_number} #{color.name}' style='display:none'/>
          </label>
        </li>"
      end
    elsif color_palette.name == "Wood"
      color_palette.colors.each do |color|
      list_items += "<li style='display:inline-block;margin: 0 8px; width: 50px;' class='has-tip' data-tooltip title='#{display_color_number color.color_number} #{color.name} #{color.color_foundation}'>               
          <label class='color-label' style='background: url(/assets/wood/#{color.color_number}.jpg)' data-color='#{color.hex}'>
            <input type='checkbox' data-sku='#{@profile.uuid.gsub('XXX', display_color_number(color.color_number))}' value='#{display_color_number color.color_number} #{color.name}' style='display:none'/>
          </label>
        </li>"
      end
    elsif color_palette.name == "Stone"
      color_palette.colors.each do |color|
      list_items += "<li style='display:inline-block;margin: 0 8px; width: 50px;' class='has-tip' data-tooltip title='#{color.color_number} #{color.name} #{color.color_foundation}'>               
          <label class='color-label' style='background: url(/assets/stone/#{color.color_number}.jpg)' data-color='#{color.hex}'>
            <input type='checkbox' data-sku='#{@profile.uuid.gsub('XXX', color.color_number)}' value='#{color.color_number} #{color.name}' style='display:none'/>
          </label>
        </li>"
      end
    else
      color_palette.colors.each do |color|
      list_items += "<li style='display:inline-block;margin: 0 8px; width: 50px;' class='has-tip' data-tooltip title='#{display_color_number color.color_number} #{color.name} #{color.color_foundation}'>               
          <label class='color-label' style='background: ##{color.hex}' data-color='#{color.hex}'>
            <input type='checkbox' data-sku='#{@profile.uuid.gsub('XXX', display_color_number(color.color_number))}' value='#{display_color_number color.color_number} #{color.name}' style='display:none'/>
          </label>
        </li>"
      end
    end

    list_items.html_safe
  end

  def image_for(profile, options={})
    if options[:type] == 'profile'
      folder = "profile_images"
      image_suffex = "profile"
    elsif options[:type] == 'corner'
      folder = "corner_images"
      image_suffex = "image"
    end

    if File.exists?(File.join(Rails.root, "app/assets/images/#{folder}/#{profile.style_type.name.capitalize}-#{profile.name}-#{image_suffex}.jpg"))
      image_tag "/assets/#{folder}/#{profile.style_type.name.capitalize}-#{profile.name}-#{image_suffex}.jpg", class: options[:class]
    else
      image_tag "missing.jpg", class: options[:class]
    end
  end

  def image_for_results(style_type)
    if File.exists?(File.join(Rails.root, "app/assets/images/profile_images/#{style_type.name.capitalize}-#{style_type.profiles.first.name}-profile.jpg"))
      image_tag "/assets/profile_images/#{style_type.name.capitalize}-#{style_type.profiles.first.name}-profile.jpg", class: "left has-tip result-profile-image", title: "Choose a profile from the dropdown to see more details!", data: {tooltip:  ''}
    else
      image_tag "missing.jpg", class: "left has-tip result-profile-image", title: "Choose a profile from the dropdown to see more details!", data: {tooltip:  ''}
    end
  end

  def icons_for_collection(collection)
    image_div = ""
    if @profile.collection.icon_1
      image_div << image_tag("Icon_BIAQ.png")
      image_div << "<br /><br />"
    end
    if @profile.collection.icon_2
      image_div << image_tag("icon_floorscore.png")
      image_div << "<br /><br />"
    end
    if @profile.collection.icon_3
      image_div << image_tag("icon_NSF.png")
      image_div << "<br /><br />"
    end
    if @profile.collection.icon_4
      image_div << image_tag("icon_phthalateFree.png")
      image_div << "<br /><br />"
    end
    if @profile.collection.icon_5
      image_div << image_tag("icon_phthalateHalogen.png")
    end
    image_div.html_safe
  end

  def color_swatch_for(color_palette)
    divs = ""
    if color_palette.name.downcase == "selects"            
      Color.where(:selects => true).order(:color_number).each do |color|
        divs += "<div class='large-3 columns color-swatch'><div class='swatch shadow' style='background: ##{color.hex};'></div><br />
                       <b>#{display_color_number color.color_number}</b> #{color.name}<b> #{color.color_foundation}</b> #{in_selects? color}<br />"
        divs += "</div>"
      end
    elsif color_palette.name.downcase == "wall art"            
      color_palette.colors.order(:color_number).each do |color|
        divs += "<div class='large-3 columns color-swatch'><div class='swatch shadow' style='background: url(/assets/wallart/#{color.color_number}.jpg);'></div><br />
                       <b>#{color.color_number}</b> #{color.name}<b> #{color.color_foundation}</b> #{in_selects? color}<br />"
        divs += "</div>"
      end
    elsif color_palette.name.downcase == "w"            
      color_palette.colors.order(:color_number).each do |color|
        divs += "<div class='large-3 columns color-swatch'><div class='swatch shadow' style='background: url(/assets/wallart/#{color.color_number}.jpg);'></div><br />
                       <b>#{color.color_number}</b> #{color.name}<b> #{color.color_foundation}</b> #{in_selects? color}<br />"
        divs += "</div>"
      end
    elsif color_palette.name.downcase == "wood"            
      color_palette.colors.order(:color_number).each do |color|
        divs += "<div class='large-3 columns color-swatch'><div class='swatch shadow' style='background: url(/assets/wood/#{color.color_number}.jpg);'></div><br />
                       <b>#{color.color_number}</b> #{color.name}<b> #{color.color_foundation}</b> #{in_selects? color}<br />"
        divs += "</div>"
      end
    elsif color_palette.name.downcase == "stone"            
      color_palette.colors.order(:color_number).each do |color|
        divs += "<div class='large-3 columns color-swatch'><div class='swatch shadow' style='background: url(/assets/stone/#{color.color_number}.jpg);'></div><br />
                       <b>#{color.color_number}</b> #{color.name}<b> #{color.color_foundation}</b> #{in_selects? color}<br />"
        divs += "</div>"
      end
    else
      color_palette.colors.order(:color_number).each do |color|
        divs += "<div class='large-3 columns color-swatch'><div class='swatch shadow' style='background: ##{color.hex};'></div><br />
                       <b>#{display_color_number color.color_number}</b> #{color.name}<b> #{color.color_foundation}</b> #{in_selects? color}<br />"
        divs += "</div>"
      end
    end

    divs.html_safe
  end

  def color_name_with_text(color_name)
    case color_name
    when 'Wood'
      'Masquerade (Standard)'
    when 'Stone'
      'hide'
    when 'Wall Art'
      color_name
    else
      color_name.gsub(/$W/, "Wall Art")
    end
  end
end

app/views/filters/_details.html.erb
    <div class="row">
      <div class="large-12 columns">
        <%= link_to "« back to filter", "javascript:void(0)", class: 'back-to-filter right small button secondary' %>
        <h4><%= @profile.style_type.name %></h4>
        <h5 class="subheader"><%= @profile.collection.name %></h5>
        <div class="large-4 columns">
          <%= image_tag @profile.corner_image_url, class: 'profile-image' %>          
        </div>
        <div class="large-4 columns" style="text-align: center">
          <%= image_tag @profile.profile_image_url, class: 'profile-image' %>
          <%= @profile.name %><br />
          <%= @profile.size %>"
        </div>
        <div class="large-4 columns">
          <%= link_to "Add #{pluralize 0, 'sample'} to cart", 'javascript:void(0)', class: 'medium button full-width', id: 'addLink', disabled: 'disabled', data: {confirm: "Are you ready to leave this page?"} %>
          <p><b>Selected Colors:</b></p>
          <%= form_tag sample_cart_path, id: 'sampleCart' do %>
            <ul id='selectedColors'>
              <li></li>
            </ul>
          <% end %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="large-12 columns">
        <h4>Colors and Patterns</h4>
      </div>
    </div>
    <div class="row">
      <div class="large-12 columns">
        <div class="section-container tabs" data-section>
          <% @profile.color_palettes.each do |c| %>
            <% unless color_name_with_text(c.name) == 'hide' %>
              <section class="section <%= c.id == @profile.color_palettes.first.id ? 'active' : '' %>">          
                <p class="title" style="width: <%= @profile.color_palette_width_in_percent %>"><a href="#"><%= color_name_with_text c.name %></a></p>
                <div class="content">                 
                  <%= '<p>Wood</p>'.html_safe if c.name == 'Wood' %>                  
                  <ul>
                    <%= colors_for c %>               
                  </ul>
                  <% if c.name == 'Wood' %>
                    <p>Stone</p>
                    <% @profile.color_palettes.where(name: 'Stone').each do |s| %>
                      <ul>
                        <%= colors_for s %>               
                      </ul>
                    <% end %>
                  <% end %>
                </div>
              </section>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="large-12 columns">
        <h4><%= @profile.collection.name %></h4>
        <p><%= @profile.collection.collection_description %></p>
      </div>
    </div>
    <div class="row">
      <div class="large-8 columns">
        <% @profile.collection.collection_sections.each do |cs| %>
          <h5><%= cs.title %></h5>
          <%= cs.pretty_body %>
        <% end %>
      </div>      
      <div class="large-4 columns">
        <br />
        <%= icons_for_collection @profile.collection %>
      </div>
    </div>

     <div class="row">
      <hr />
    <% unless @profile.related_products.blank? %>
      <h5>Other <%= @profile.collection.name %> Products</h5>
      <ul>
          <% @profile.related_products.each do |related_style| %>
            <li class="related-products"><%= image_tag related_style.profiles.first.corner_image_url %><br /><%= related_style.name %></li>
          <% end %>
      <ul>
      <% end %>
      <br />      
    </div>
    <div id="samplecart-results"></div>

app/views/filters/_results.html.erb
<% unless @style_types.blank? %>

  <% @style_types.each_with_index do |style_type,index| %>
    <div class='row'>
      <div class="animated fadeInLeft large-3 columns">        
        <%= image_tag style_type.profiles.first.profile_image_url, class: "has-tip result-profile-image", title: "Choose a profile from the dropdown to see more details!", data: {tooltip:  ''} %>
      </div>
      <div class='animated fadeInLeft large-3 columns' style='z-index: <%= 100 - index %>'>
        <ul>
          <li><%= style_type.collection.name %></li>
          <li class="name"><b><%= style_type.name.upcase %></b></li>      
          <li class="name"><b><%= style_type.material.upcase %></b></li>      
          <li style="margin-top: 30px;">
            <%= form_tag root_path, class: 'details-form custom', data: {remote: true} do %>
              <%= label_tag :profile_id, nil, for: 'detail-select', class: 'hide' %>
              <%= select_tag :profile_id, options_for_select(style_type.profiles.map {|pf| ["#{pf.name} - #{pf.size}\"", pf.id]} ), prompt: 'select a profile', id: 'detail-select', class: 'small' %>
              <div class="custom dropdown small"><a href="#" class="current">select a profile</a><a href="#" class="selector"></a><ul><li class="selected">select a profile</li><li>MW-7-C</li></ul></div>
            <% end %>
          </li>
        </ul>
      </div>
      <div class='large-6 columns'>
        <% style_type.profiles.each do |p| %>
        <div class='row profile-row'>
          <div class="animated fadeInRight large-4 columns">
            <%= p.name %>
          </div>    
          <div class="animated fadeInRight large-8 columns clearfix profile-row">
            <% p.color_palettes.ordered.each do |cp| %>
              <span class="color-palette color-palette-<%= cp.name.gsub('Wall Art', 'wall-art') %>"><%= cp.name == 'Selects' ? '&nbsp;'.html_safe : cp.name %></span>
            <% end %>
            <br style="clear:both" />
            <br style="clear:both" />        
          </div>
        </div>
        <% end %>
      </div>
    </div>
    <hr />
  <% end %>

<% else %>

  <h1 class='animated bounceInDown no-results'>there were no results</h1>

<% end %>

app/views/filters/_samplecart.html.erb
<a href="javascript:void(0)" id="notification-close" style="float: right; padding: 8px;">X</a>
<%= @results.html_safe %>

app/views/filters/_search.html.erb
<%= form_tag root_path, id: 'search-form', class: 'custom', data: {remote: true} do %>
  <div id="collections">
    <%= select_tag :collection_id, options_for_select(@collections.map {|c| [c.name, c.id]}, selected: params[:collection_id]), prompt: 'select a collection', class: ' filter-select full-width' %>
  </div>

  <% cache([@color_palettes]) do %>
  <div id="color">
    <h6>COLOR</h6>
    <% @color_palettes.each do |color_palette| %>
      <% unless nice_checkbox_palette_name_for(color_palette) == 'hide' %>
        <label for="<%= color_palette.id %>">
          <%= check_box_tag 'color_palette_ids[]', color_palette.id, (params[:color_palette_ids] && params[:color_palette_ids].include?(color_palette.id.to_s)), id: color_palette.id %> <%= nice_checkbox_palette_name_for color_palette %>
        </label>
      <% end %>
    <% end %>
    <label style="padding:0">
    </label>
  </div>
  <% end %>

  <% cache([@materials]) do %>
    <br />
    <div id="material">
      <%= select_tag :material, options_for_select(@materials, selected: params[:material]), prompt: 'select a material', class: ' filter-select full-width' %>      
    </div>
  <% end %>

  <% cache([@style_names]) do %>
    <div id="style-type">
      <%= select_tag :style_type_name, options_for_select(@style_names, selected: params[:style_type_name]), prompt: 'select a style', class: ' filter-select full-width' %>
    </div>  
  <% end %>
<% end %>

app/views/filters/color_palettes.html.erb
<style>
.swatch {
  width: 50px;
  height: 50px;
  margin: 0 auto;
  border: 3px solid whitesmoke;
}
.centered {
  text-align: center;
}
.shadow {
  box-shadow: 0 1px 3px #AAA;
}

.color-swatch {
  margin-top: 12px;
  padding-bottom: 20px;
  text-align: center;
  border-bottom: 1px solid #CCC;
}
.red {
  color: red;
}
</style>

<script>
$('#palette-select').live('change', function() {
  var cp = $(this).val();  
  $(".title").each(function() {
    if($(this).text().trim()==cp)
      $(this).click();
  });
});
</script>

<h3 class="left subheader">List of Color Palettes</h3>
<%= link_to "« back to filter", root_path, class: 'back-to-filter right small button secondary' %>
<hr />
<br />

<%= select_tag :color_palette, options_for_select( @color_palettes.map { |cp| cp.name } ), id: 'palette-select', class: 'show-for-small' %>
<br />

<div class="section-container tabs" data-section>
<% @color_palettes.each do |color_palette| %>  
  <% if color_palette.id.to_s == params[:color_palette_id].to_s %>
    <section class="section active">
  <% else %>
    <section class="section">
  <% end %>

    <div class="title hide-for-small" style="width: 11%">        
      <h5 style="text-align: center"><%= color_palette.name %></h5>        
    </div>

    <div class="content">
      <br />
      <div class="row">
        <div class="large-3 columns">
          <h4 class="centered"><%= color_palette.name %></h4>
        </div>        
        <div class="large-5 large-offset-4 columns">
        </div>
        <hr />
      </div>
      <div class="row">
        <%= color_swatch_for color_palette %>
      </div>
    </div>
  </section>
<% end %>
</div>

app/views/filters/index.html.erb
<div class="row">
  <div id="filter-form" class="large-4 columns">
    <%= link_to "Reset", 'javascript:void(0)', id: 'reset' %>
    <h4>FILTER BY:</h4>    
    <div id="search" class="ajax-container search">
      <%= render 'search' %>
    </div>
    <% cache do %>
    <div class='color-legend'>      
      <% ColorPalette.labels.each do |cp| %>
      <div class='row'>
        <div class='large-2 columns color-palette-list'>
          <span class="color-palette round color-palette-<%= cp.name %>" style="left:20px !important"><%= cp.name %></span>
        </div>
        <div class='large-10 columns' style="padding: 0">
           - <%= link_to nice_color_palette_name_for(cp), color_palette_chart_path %>
         </div>
      </div>
      <br />
      <% end %>
    </div>
    <% end %>
  </div>

  <% cache([OpeningPage.first]) do %>
  <div class="result-parent animated large-8 columns">
    <div id="header-row" class="row hide">
      <div class="large-6 columns"><h4>WALLBASE</h4></div>
      <div class="large-6 columns">
        <div class="large-4 columns"><h5>SKU</h5></div>
        <div class="large-8 columns"><h5>Color Palettes</h5></div>
      </div>
    </div>
    <div id="results" class="ajax-container results">      
      <%= OpeningPage.first.body.html_safe %>
    </div>
  </div>

  <div class="single-parent large-8 columns animated">
    <div id="details" class="ajax-container details"></div>
  </div>
  <% end %>
</div>

app/views/filters/index.js.erb
<% if params[:profile_id].present? %>
  $(".ajax-container.details").html("<%= escape_javascript(render("details")) %>");
  $(window).trigger("resize");
  $('#filter-form').fadeTo('slow', 0.2);
<% else %>
  $(".ajax-container.results").html("<%= escape_javascript(render("results")) %>");
  $('select').hide();
  $.ajax({complete: function () {$(document).foundation();}});
  $('#filter-form').fadeTo('slow', 1);
<% end %>

app/views/filters/samplecart.js.erb
$('#samplecart-results').html($("<%= escape_javascript(render("samplecart")) %>"))
$('#samplecart-results').fadeIn()