config/routes.rb
Wallbase::Application.routes.draw do
  resources :opening_pages

  # Main resources
  resources :collections
  resources :collection_sections
  resources :style_types, :path => "style-types"
  resources :profiles
  resources :colors
  resources :color_palettes, :path => "color-palettes"

  # Johnsonite API routes
  match '/samplecart' => 'filters#samplecart', as: 'sample_cart', via: [:get, :post]

  # Root path
  root :to => 'filters#index'
  post '/' => 'filters#index'
  get '/color-pallete-chart' => 'filters#color_palettes', as: 'color_palette_chart'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <style>input {display:inline-block !important;}</style><![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <style>input {display:inline-block !important;}</style><![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <style>input {display:inline-block !important;}</style><![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />
  
  <!-- Uncomment to make IE8 render like IE7 -->
  <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
  
  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no, width=device-width" />  
  <title>Johnsonite</title>
  
  <!-- Included CSS Files -->
  <%= stylesheet_link_tag    "application" %>
  
  <!-- Included JS Files  -->
  <%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>
<!--[if (gte IE 9)|!(IE)]><!-->
  <!-- Apple Web App Stuff -->
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <!-- iPad ICON-->
  <link href="apple-touch-icon-72x72.png" sizes="72x72" rel="apple-touch-icon">
  <!-- iPhone (Retina) ICON-->
  <link href="apple-touch-icon-114x114.png" sizes="114x114" rel="apple-touch-icon">
  <!-- iPad (Retina) ICON-->
  <link href="apple-touch-icon-144x144.png" sizes="144x144" rel="apple-touch-icon">

  <!-- iPhone SPLASHSCREEN-->
  <link href="apple-touch-startup-image-320x460.png" media="(device-width: 320px)" rel="apple-touch-startup-image">
  <!-- iPhone (Retina) SPLASHSCREEN-->
  <link href="apple-touch-startup-image-640x920.png" media="(device-width: 320px) and (-webkit-device-pixel-ratio: 2)" rel="apple-touch-startup-image">
  <!-- iPad (portrait) SPLASHSCREEN-->
  <link href="apple-touch-startup-image-768x1004.png" media="(device-width: 768px) and (orientation: portrait)" rel="apple-touch-startup-image">
  <!-- iPad (landscape) SPLASHSCREEN-->
  <link href="apple-touch-startup-image-748x1024.png" media="(device-width: 768px) and (orientation: landscape)" rel="apple-touch-startup-image">
  <!-- iPad (Retina, portrait) SPLASHSCREEN-->
  <link href="apple-touch-startup-image-1536x2008.png" media="(device-width: 1536px) and (orientation: portrait) and (-webkit-device-pixel-ratio: 2)" rel="apple-touch-startup-image">
  <!-- iPad (Retina, landscape) SPLASHSCREEN-->
  <link href="apple-touch-startup-image-1496x2048.png" media="(device-width: 1536px)  and (orientation: landscape) and (-webkit-device-pixel-ratio: 2)" rel="apple-touch-startup-image">
  <!-- END Apple Web App -->
<!--<![endif]-->
  <script>
    $(document).ready( function() {
      $('input:visible').first().focus();
    });
  </script>
</head>
  <body>
    <% if flash[:notice] %>
      <div class='alert-box success'><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:error] %>
      <div class='alert-box error'><%= flash[:error] %></div>
    <% end %>


  <div class="fixed">
    <nav class="top-bar">
      <ul class="title-area">
        <!-- Title Area -->
        <li class="name">
          <h1><%= link_to "Wallbase Filter CMS", collections_path %></h1>
        </li>
        <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>

      <section class="top-bar-section">
        <!-- Left Nav Section -->
        <ul class="right">
          <li class="divider show-for-medium-and-up"></li>
          <li>
            <%= link_to "Color Palettes", color_palettes_path %>
          </li>
        </ul>
        <ul class="right">
          <li class="divider show-for-medium-and-up"></li>
          <li>
            <%= link_to "Collections", collections_path %>
          </li>
        </ul>
        <ul class="right">
          <li class="divider show-for-medium-and-up"></li>
          <li>
            <%= link_to "Opening Page", opening_pages_path %>
          </li>
        </ul>
      </section>
    </nav>
  </div>

<div id="fader" class="fixed" style="top: 45px">
  <br />
  <br />
  <br />
</div>

<div class="row">
  <div class="large-12 columns">
    <br />
    <br />
    <br />
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/layouts/filter.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <style>input {display:inline-block !important;}</style><![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <style>input {display:inline-block !important;}</style><![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <style>input {display:inline-block !important;}</style><![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />
  
  <!-- Uncomment to make IE8 render like IE7 -->
  <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
  
  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no, width=device-width" />  
  <title>Johnsonite</title>
  
  <!-- Included CSS Files -->
  <%= stylesheet_link_tag    "application" %>
  
  <!-- Included JS Files  -->
  <%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>
<!--[if (gte IE 9)|!(IE)]><!-->
  <!-- Apple Web App Stuff -->
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <!-- iPad ICON-->
  <link href="apple-touch-icon-72x72.png" sizes="72x72" rel="apple-touch-icon">
  <!-- iPhone (Retina) ICON-->
  <link href="apple-touch-icon-114x114.png" sizes="114x114" rel="apple-touch-icon">
  <!-- iPad (Retina) ICON-->
  <link href="apple-touch-icon-144x144.png" sizes="144x144" rel="apple-touch-icon">

  <!-- iPhone SPLASHSCREEN-->
  <link href="apple-touch-startup-image-320x460.png" media="(device-width: 320px)" rel="apple-touch-startup-image">
  <!-- iPhone (Retina) SPLASHSCREEN-->
  <link href="apple-touch-startup-image-640x920.png" media="(device-width: 320px) and (-webkit-device-pixel-ratio: 2)" rel="apple-touch-startup-image">
  <!-- iPad (portrait) SPLASHSCREEN-->
  <link href="apple-touch-startup-image-768x1004.png" media="(device-width: 768px) and (orientation: portrait)" rel="apple-touch-startup-image">
  <!-- iPad (landscape) SPLASHSCREEN-->
  <link href="apple-touch-startup-image-748x1024.png" media="(device-width: 768px) and (orientation: landscape)" rel="apple-touch-startup-image">
  <!-- iPad (Retina, portrait) SPLASHSCREEN-->
  <link href="apple-touch-startup-image-1536x2008.png" media="(device-width: 1536px) and (orientation: portrait) and (-webkit-device-pixel-ratio: 2)" rel="apple-touch-startup-image">
  <!-- iPad (Retina, landscape) SPLASHSCREEN-->
  <link href="apple-touch-startup-image-1496x2048.png" media="(device-width: 1536px)  and (orientation: landscape) and (-webkit-device-pixel-ratio: 2)" rel="apple-touch-startup-image">
  <!-- END Apple Web App -->
<!--<![endif]-->
  <style>
  .alert-box {
    width: 400px !important;
    margin: 0 auto !important;
    top: 10% !important;
    position: fixed;
    z-index: 99999999 !important;
    text-align: center;
    left: 45%;
    padding: 28px !important;
    background: #005294 !important;
    box-shadow: 0 1px 3px #AAA;
    font-size: 18pt;
    border: 1px solid #333 !important;
  }
  </style>
</head>
  <body>
    <% if flash[:notice] %>
      <div class='alert-box success'><%= flash[:notice] %></div>
    <% end %>

    <div class="row">
      <div class="large-12 columns">
        <br />
        <%= yield %>
      </div>
    </div>
</body>
</html>